/* eslint-disable import/prefer-default-export */
export const SET_MODAL_SIGN_UP = 'SET_MODAL_SIGN_UP';
export const SET_MODAL_LOG_IN = 'SET_MODAL_LOG_IN';
export const TOGGLE_BAG_POPUP = 'TOGGLE_BAG_POPUP';
export const REQUEST_PRODUCTS_IN_CART = 'REQUEST_PRODUCTS_IN_CART';
export const SET_PRODUCTS_IN_CART = 'SET_PRODUCTS_IN_CART';
export const ERROR_REQUEST_PRODUCTS_IN_CART = 'ERROR_REQUEST_PRODUCTS_IN_CART';
export const REQUEST_REMOVE_PRODUCT_FROM_CART =
  'REQUEST_REMOVE_PRODUCT_FROM_CART';
export const SUCCESS_REMOVE_PRODUCT_FROM_CART =
  'SUCCESS_REMOVE_PRODUCT_FROM_CART';
export const ERROR_REMOVE_PRODUCT_FROM_CART = 'ERROR_REMOVE_PRODUCT_FROM_CART';
export const LOAD_ITEMS_REQUEST = 'LOAD_ITEMS_REQUEST';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const SET_ITEMS = 'SET_ITEMS';
export const SET_ITEM = 'SET_ITEM';
