/* eslint-disable import/prefer-default-export */
export const SET_MODAL_SIGN_UP = 'SET_MODAL_SIGN_UP';
export const SET_MODAL_LOG_IN = 'SET_MODAL_LOG_IN';
export const TOGGLE_BAG_POPUP = 'TOGGLE_BAG_POPUP';
export const REQUEST_PRODUCTS_IN_CART = 'REQUEST_PRODUCTS_IN_CART';
export const SET_PRODUCTS_IN_CART = 'SET_PRODUCTS_IN_CART';
export const ERROR_REQUEST_PRODUCTS_IN_CART = 'ERROR_REQUEST_PRODUCTS_IN_CART';
export const REQUEST_REMOVE_PRODUCT_FROM_CART =
  'REQUEST_REMOVE_PRODUCT_FROM_CART';
export const SUCCESS_REMOVE_PRODUCT_FROM_CART =
  'SUCCESS_REMOVE_PRODUCT_FROM_CART';
export const ERROR_REMOVE_PRODUCT_FROM_CART = 'ERROR_REMOVE_PRODUCT_FROM_CART';
export const TOGGLE_ACCOUNT_ERROR = 'TOGGLE_ACCOUNT_ERROR';
export const TOGGLE_ACCOUNT_MODAL = 'TOGGLE_ACCOUNT_MODAL';
export const SET_MODAL_FORGOT_PASSWORD = 'SET_MODAL_FORGOT_PASSWORD';

export const GET_BLOG_POSTS = 'GET_BLOG_POSTS';

export const LOAD_ITEMS_REQUEST = 'LOAD_ITEMS_REQUEST';
export const LOAD_ITEMS_SUCCESS = 'LOAD_ITEMS_SUCCESS';
export const SET_ITEMS = 'SET_ITEMS';
export const SET_ITEM = 'SET_ITEM';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const FILTERED_PRODUCTS = 'FILTERED_PRODUCTS';
export const CLEAR_FILTERED_PRODUCTS = 'CLEAR_FILTERED_BY_VALUE';
export const FILTER_SIZE = 'FILTER_SIZE';
export const FILTER_COLOR = 'FILTER_COLOR';
export const FILTER_FABRIC = 'FILTER_FABRIC';
export const FILTER_CATALOG = 'FILTER_CATALOG';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const SET_SELECTED_OPTION = 'SET_SELECTED_OPTION';

export const SET_MIN_SLIDER_VALUE = 'SET_MIN_SLIDER_VALUE';
export const SET_MAX_SLIDER_VALUE = 'SET_MAX_SLIDER_VALUE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_PER_PAGE = 'SET_PER_PAGE';

export const SET_CART = 'SET_CART';

export const SET_QUANTITY = 'SET_QUANTITY';
export const SET_CART_AFTER_DELETE = 'SET_CART_AFTER_DELETE';

export const CLEAR_CART = 'CLEAR_CART';

export const TOGGLE_WISHLIST = 'TOGGLE_WISHLIST';
export const REQUEST_SET_WISHLIST_PRODUCTS = 'REQUEST_SET_WISHLIST_PRODUCTS';
export const SET_WISHLIST_PRODUCTS = 'SET_WISHLIST_PRODUCTS';
export const ERROR_SET_WISHLIST_PRODUCTS = 'ERROR_SET_WISHLIST_PRODUCTS';
export const REQUEST_REMOVE_PRODUCT_FROM_WISHLIST =
  'REQUEST_REMOVE_PRODUCT_FROM_WISHLIST';
export const SUCCESS_REMOVE_PRODUCT_FROM_WISHLIST =
  'SUCCESS_REMOVE_PRODUCT_FROM_WISHLIST';
export const ERROR_REMOVE_PRODUCT_FROM_WISHLIST =
  'ERROR_REMOVE_PRODUCT_FROM_WISHLIST';
export const REQUEST_ADD_PRODUCT_TO_WISHLIST =
  'REQUEST_ADD_PRODUCT_TO_WISHLIST';
export const SUCCESS_ADD_PRODUCT_TO_WISHLIST =
  'SUCCESS_ADD_PRODUCT_TO_WISHLIST';
export const ERROR_ADD_PRODUCT_TO_WISHLIST = 'ERROR_ADD_PRODUCT_TO_WISHLIST';
export const FILTER_NAME = 'FILTER_NAME';
